import { useState } from 'react';
import { AIPlan, DailyData, UserProfile } from '@/types/fitness';
import { ProgressBar } from '@/components/shared/ProgressBar';
import { ScoreRing } from '@/components/shared/ScoreRing';

interface ProgressPageProps {
  profile: UserProfile;
  plan: AIPlan;
  bmiHistory: { date: string; bmi: number }[];
  measurements: { date: string; type: string; value: number }[];
  streak: number;
  bestStreak: number;
  weekMeals: Record<string, number>;
  workoutHistory: Record<string, string[]>;
}

export function ProgressPage({
  profile, plan, bmiHistory, measurements, streak, bestStreak, weekMeals, workoutHistory,
}: ProgressPageProps) {
  const [measureType, setMeasureType] = useState('weight');

  const weightLost = profile.weight - (measurements.filter(m => m.type === 'weight').pop()?.value || profile.weight);
  const toGo = Math.abs((measurements.filter(m => m.type === 'weight').pop()?.value || profile.weight) - profile.targetWeight);

  const printReport = (type: string) => {
    const w = window.open('', '_blank');
    if (!w) return;
    
    let html = `<html><head><title>FitTamil AI - ${type} Report</title>
      <style>body{font-family:sans-serif;max-width:600px;margin:40px auto;padding:20px}
      h1{color:#7C3AED}h2{color:#00D4FF;margin-top:24px}
      table{width:100%;border-collapse:collapse;margin:12px 0}
      td,th{border:1px solid #ddd;padding:8px;text-align:left}
      .stat{display:inline-block;margin:8px;padding:12px;border:1px solid #ddd;border-radius:8px;min-width:100px;text-align:center}
      </style></head><body>`;

    if (type === 'Progress') {
      html += `<h1>📈 Progress Report</h1>
        <p><strong>${profile.name}</strong> — ${new Date().toLocaleDateString()}</p>
        <h2>Weight Journey</h2>
        <div class="stat"><div>Start</div><div><strong>${profile.weight}kg</strong></div></div>
        <div class="stat"><div>Lost</div><div><strong>${Math.abs(weightLost).toFixed(1)}kg</strong></div></div>
        <div class="stat"><div>To Go</div><div><strong>${toGo.toFixed(1)}kg</strong></div></div>
        <h2>Streaks</h2><p>Current: ${streak} days | Best: ${bestStreak} days</p>
        <h2>BMI History</h2><table><tr><th>Date</th><th>BMI</th></tr>
        ${bmiHistory.map(b => `<tr><td>${b.date}</td><td>${b.bmi}</td></tr>`).join('')}</table>`;
    } else if (type === 'Meal Plan') {
      html += `<h1>🍽️ Meal Plan Report</h1>
        <p><strong>${profile.name}</strong> — Daily target: ${plan.dailyCalories} kcal</p>
        <h2>Daily Meals</h2><table><tr><th>Time</th><th>Meal</th><th>Foods</th><th>Cal</th></tr>
        ${plan.meals.map(m => `<tr><td>${m.time}</td><td>${m.name}</td><td>${m.foods}</td><td>${m.calories}</td></tr>`).join('')}</table>
        <h2>✅ Do Eat</h2><ul>${plan.doEat.map(d => `<li>${d}</li>`).join('')}</ul>
        <h2>❌ Avoid</h2><ul>${plan.avoidEat.map(a => `<li>${a}</li>`).join('')}</ul>
        <h2>Smart Swaps</h2><table><tr><th>From</th><th>To</th><th>Saved</th></tr>
        ${plan.foodSwaps.map(s => `<tr><td>${s.from}</td><td>${s.to}</td><td>${s.saved} kcal</td></tr>`).join('')}</table>`;
    } else {
      html += `<h1>📋 My Plan Report</h1>
        <p><strong>${profile.name}</strong></p>
        <h2>Numbers</h2>
        <div class="stat"><div>BMR</div><div><strong>${plan.bmr}</strong></div></div>
        <div class="stat"><div>TDEE</div><div><strong>${plan.tdee}</strong></div></div>
        <div class="stat"><div>Calories</div><div><strong>${plan.dailyCalories}</strong></div></div>
        <div class="stat"><div>Water</div><div><strong>${plan.dailyWater}ml</strong></div></div>
        <h2>Strategy</h2><p>${plan.coachNotes.strategy}</p>
        <h2>Milestones</h2><ul>${plan.milestones.map(m => `<li>Week ${m.week}: ${m.goal}</li>`).join('')}</ul>`;
    }

    html += `<p style="margin-top:40px;color:#999;text-align:center">Generated by FitTamil AI</p></body></html>`;
    w.document.write(html);
    w.document.close();
    w.print();
  };

  const filteredMeasurements = measurements.filter(m => m.type === measureType);

  return (
    <div className="space-y-5 animate-fade-up">
      {/* PDF Reports */}
      <div className="grid grid-cols-3 gap-2">
        {['Progress', 'Meal Plan', 'My Plan'].map(type => (
          <button key={type} onClick={() => printReport(type)}
            className="ft-card text-center py-4 hover:border-primary/30 active:scale-95 transition-all">
            <div className="text-2xl mb-1">{type === 'Progress' ? '📈' : type === 'Meal Plan' ? '🍽️' : '📋'}</div>
            <div className="text-xs font-medium">{type}</div>
            <div className="text-[10px] text-muted-foreground">PDF</div>
          </button>
        ))}
      </div>

      {/* Weight Journey */}
      <div className="ft-card">
        <h3 className="font-heading text-xl mb-3">⚖️ Weight Journey</h3>
        <div className="grid grid-cols-4 gap-2 text-center">
          <div className="rounded-lg bg-muted/50 p-3">
            <div className="text-xs text-muted-foreground">Start</div>
            <div className="font-mono font-bold">{profile.weight}kg</div>
          </div>
          <div className="rounded-lg bg-muted/50 p-3">
            <div className="text-xs text-muted-foreground">Current</div>
            <div className="font-mono font-bold">
              {filteredMeasurements.length > 0 ? `${filteredMeasurements[filteredMeasurements.length - 1].value}kg` : `${profile.weight}kg`}
            </div>
          </div>
          <div className="rounded-lg bg-muted/50 p-3">
            <div className="text-xs text-muted-foreground">Lost</div>
            <div className="font-mono font-bold text-ft-emerald">{Math.abs(weightLost).toFixed(1)}kg</div>
          </div>
          <div className="rounded-lg bg-muted/50 p-3">
            <div className="text-xs text-muted-foreground">To Go</div>
            <div className="font-mono font-bold text-ft-amber">{toGo.toFixed(1)}kg</div>
          </div>
        </div>
        <div className="mt-3">
          <ProgressBar
            value={Math.abs(weightLost)}
            max={Math.abs(profile.weight - profile.targetWeight) || 1}
            variant="success"
            label="Progress"
            showValue
          />
        </div>
      </div>

      {/* Streaks */}
      <div className="grid grid-cols-2 gap-3">
        <div className="ft-card text-center">
          <div className="text-3xl mb-1">🔥</div>
          <div className="font-mono text-2xl font-bold">{streak}</div>
          <div className="text-xs text-muted-foreground">Current Streak</div>
        </div>
        <div className="ft-card text-center">
          <div className="text-3xl mb-1">🏆</div>
          <div className="font-mono text-2xl font-bold">{bestStreak}</div>
          <div className="text-xs text-muted-foreground">Best Streak</div>
        </div>
      </div>

      {/* BMI History */}
      {bmiHistory.length > 0 && (
        <div className="ft-card">
          <h3 className="font-heading text-xl mb-3">📊 BMI History</h3>
          <div className="space-y-2">
            {bmiHistory.slice(-5).map((b, i) => (
              <div key={i} className="flex justify-between text-sm">
                <span className="text-muted-foreground">{b.date}</span>
                <span className="font-mono font-semibold">{b.bmi}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Measurements */}
      <div className="ft-card">
        <h3 className="font-heading text-xl mb-3">📏 Measurements</h3>
        <div className="flex gap-2 overflow-x-auto pb-2 mb-3">
          {['weight', 'waist', 'body fat', 'bp', 'heart rate'].map(t => (
            <button key={t} onClick={() => setMeasureType(t)}
              className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-medium transition-all capitalize ${
                measureType === t ? 'gradient-primary text-background' : 'border border-border text-muted-foreground'
              }`}>
              {t}
            </button>
          ))}
        </div>
        {filteredMeasurements.length > 0 ? (
          <div className="space-y-2">
            {filteredMeasurements.slice(-10).map((m, i) => (
              <div key={i} className="flex justify-between text-sm">
                <span className="text-muted-foreground">{m.date}</span>
                <span className="font-mono">{m.value}</span>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-4">No {measureType} measurements yet</p>
        )}
      </div>

      {/* Weekly Meals Summary */}
      <div className="ft-card">
        <h3 className="font-heading text-xl mb-3">🍽️ Weekly Meals</h3>
        <div className="grid grid-cols-7 gap-1">
          {['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => (
            <div key={i} className="text-center">
              <div className="text-[10px] text-muted-foreground mb-1">{d}</div>
              <div className={`h-8 rounded flex items-center justify-center text-xs font-mono ${
                Object.values(weekMeals)[i] >= 4 ? 'gradient-success text-background' : 'bg-muted text-muted-foreground'
              }`}>
                {Object.values(weekMeals)[i] || 0}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Photo Journal Placeholder */}
      <div className="ft-card">
        <h3 className="font-heading text-xl mb-3">📸 Photo Journal</h3>
        <div className="grid grid-cols-3 gap-2">
          {['Week 1', 'Week 4', 'Week 8', 'Week 12', 'Month 6', 'Final'].map(label => (
            <div key={label} className="aspect-square rounded-xl bg-muted flex flex-col items-center justify-center text-center p-2">
              <span className="text-2xl mb-1">📷</span>
              <span className="text-[10px] text-muted-foreground">{label}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
